### PR TITLE
Add API to read load balancer service status

### PR DESCRIPTION
**Pull request by walbertus**
This API will retrieve the status of the load balancer service. Several structs are created in order to support the full response object of this API.

Addresses: #22
Signed-off-by: William Albertus Dembo <w.albertusd@gmail.com>

### CODE REVIEW

**Comment by walbertus** [comment]
This API follow this [doc](https://vdc-download.vmware.com/vmwb-repository/dcr-public/13f467b7-c10c-4ca6-9a02-271f02947e8e/5c714f6b-b0a1-4a08-8e32-b7ddaf59ebda/nsxt_24_api.html)

**Comment by annakhm** [comment]
Thanks @walbertus, LGTM

**Comment by walbertus** [comment]
Hi, can someone please merge this approved PR? @annakhm @asarfaty 
Thanks

**Comment by walbertus** [comment]
Is there anything else I need to do to make this PR merged?

**Comment by annakhm** [comment]
Merged. Sorry for the delay.

**Pull request merged**
